apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: nginx
  namespace: default
spec:
  provider: kubernetes
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx
  service:
    port: 80
  analysis:
    interval: 1m
    threshold: 5
    rollbackOnFailure: true
    metrics:
    - name: request-success-rate
      thresholdRange:
        min: 99
      interval: 30s
