apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: nginx
  namespace: default
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx
  service:
    port: 80
    targetPort: 80
    name: nginx
  analysis:
    interval: 30s
    threshold: 3
    maxWeight: 100
    stepWeight: 100
    metrics:
      - name: request-success-rate
        interval: 1m
        thresholdRange:
          min: 99
        templateRef:
          name: success-rate
          namespace: flagger
